"use client";

import { useState } from "react";
import Link from "next/link";
import { Download, ArrowLeft, Loader2, Sparkles } from "lucide-react";
import type { WeeklySummaryData } from "@/lib/weekly-summary";
import type { WeeklyNarrative, NarrativeLang, NarrativeContent } from "@/lib/ai/weekly-narrative-types";

type Summary = {
  id: string;
  weekStart: string;
  weekEnd: string;
  generatedAt: string;
  data: WeeklySummaryData;
};

type Strings = {
  reportTitle: string;
  weekRange: string;
  generatedAt: string;
  download: string;
  print: string;
  back: string;
  switchLang: string;
  regenerateAI: string;
  regenerating: string;
  aiUnavailable: string;
  aiGeneratedNote: string;
  // Sections
  executiveSummary: string;
  highlights: string;
  concerns: string;
  recommendations: string;
  keyNumbers: string;
  leadAcquisition: string;
  pipelineProgress: string;
  tasksWork: string;
  // Metrics
  newLeads: string;
  activities: string;
  stageChanges: string;
  tasksCreated: string;
  tasksCompleted: string;
  dealsWon: string;
  dealsLost: string;
  wonAmount: string;
  calls: string;
  meetings: string;
  emails: string;
  messages: string;
  notes: string;
  // Tables
  byAgent: string;
  byLeadType: string;
  bySource: string;
  topNewLeads: string;
  topWins: string;
  tasksCompletedList: string;
  tasksInProgressList: string;
  agentName: string;
  newLeadsCol: string;
  activitiesCol: string;
  wonDealsCol: string;
  wonAmountCol: string;
  leadName: string;
  company: string;
  amount: string;
  owner: string;
  taskTitle: string;
  type: string;
  priority: string;
  date: string;
  due: string;
  status: string;
  none: string;
  unassigned: string;
  quietWeek: string;
  byNumbers: string;
  byNarrative: string;
};

const STRINGS_HE: Strings = {
  reportTitle: "סיכום שבועי",
  weekRange: "טווח שבועי",
  generatedAt: "נוצר בתאריך",
  download: "הורדה כ-PDF",
  print: "הדפסה",
  back: "חזרה",
  switchLang: "English",
  regenerateAI: "חידוש סיכום AI",
  regenerating: "מחדש...",
  aiUnavailable: "סיכום ה-AI עדיין לא נוצר. לחץ על \"חידוש סיכום AI\" כדי ליצור אותו עכשיו.",
  aiGeneratedNote: "סיכום זה נוצר באופן אוטומטי על-ידי בינה מלאכותית בהתבסס על נתוני המערכת.",
  executiveSummary: "סיכום מנהלים",
  highlights: "נקודות בולטות",
  concerns: "נקודות לתשומת לב",
  recommendations: "המלצות לשבוע הבא",
  keyNumbers: "מספרי מפתח",
  leadAcquisition: "הזנת לידים חדשים",
  pipelineProgress: "התקדמות בצינור המכירה",
  tasksWork: "משימות וביצוע",
  newLeads: "לידים חדשים",
  activities: "פעילויות",
  stageChanges: "שינויי שלב",
  tasksCreated: "משימות שנפתחו",
  tasksCompleted: "משימות שהושלמו",
  dealsWon: "עסקאות שנסגרו",
  dealsLost: "עסקאות שאבדו",
  wonAmount: "סכום שנסגר",
  calls: "שיחות",
  meetings: "פגישות",
  emails: "אימיילים",
  messages: "הודעות",
  notes: "פתקים",
  byAgent: "פירוט לפי נציג",
  byLeadType: "לידים חדשים לפי סוג",
  bySource: "לידים חדשים לפי מקור",
  topNewLeads: "לידים חדשים בולטים",
  topWins: "סגירות בולטות",
  tasksCompletedList: "משימות שהושלמו השבוע",
  tasksInProgressList: "משימות בטיפול פעיל",
  agentName: "נציג",
  newLeadsCol: "לידים חדשים",
  activitiesCol: "פעילויות",
  wonDealsCol: "סגירות",
  wonAmountCol: "סכום",
  leadName: "ליד",
  company: "חברה",
  amount: "סכום",
  owner: "אחראי",
  taskTitle: "כותרת המשימה",
  type: "סוג",
  priority: "עדיפות",
  date: "תאריך",
  due: "תאריך יעד",
  status: "סטטוס",
  none: "אין",
  unassigned: "לא משויך",
  quietWeek: "שבוע שקט — לא נרשמו לידים, פעילויות או עסקאות בטווח התאריכים הזה.",
  byNumbers: "במספרים",
  byNarrative: "בסיפור",
};

const STRINGS_EN: Strings = {
  reportTitle: "Weekly Summary",
  weekRange: "Week of",
  generatedAt: "Generated on",
  download: "Download PDF",
  print: "Print",
  back: "Back",
  switchLang: "עברית",
  regenerateAI: "Regenerate AI Summary",
  regenerating: "Regenerating...",
  aiUnavailable: "AI summary has not been generated yet. Click \"Regenerate AI Summary\" to create one.",
  aiGeneratedNote: "This summary was auto-generated by AI based on your CRM data.",
  executiveSummary: "Executive Summary",
  highlights: "Highlights",
  concerns: "Areas of Concern",
  recommendations: "Recommendations for Next Week",
  keyNumbers: "Key Numbers",
  leadAcquisition: "Lead Acquisition",
  pipelineProgress: "Pipeline Progress",
  tasksWork: "Tasks & Work",
  newLeads: "New Leads",
  activities: "Activities",
  stageChanges: "Stage Changes",
  tasksCreated: "Tasks Created",
  tasksCompleted: "Tasks Completed",
  dealsWon: "Deals Won",
  dealsLost: "Deals Lost",
  wonAmount: "Won Amount",
  calls: "Calls",
  meetings: "Meetings",
  emails: "Emails",
  messages: "Messages",
  notes: "Notes",
  byAgent: "By Agent",
  byLeadType: "New Leads by Type",
  bySource: "New Leads by Source",
  topNewLeads: "Top New Leads",
  topWins: "Top Wins",
  tasksCompletedList: "Tasks Completed This Week",
  tasksInProgressList: "Tasks Worked On (In Progress)",
  agentName: "Agent",
  newLeadsCol: "New Leads",
  activitiesCol: "Activities",
  wonDealsCol: "Won",
  wonAmountCol: "Amount",
  leadName: "Lead",
  company: "Company",
  amount: "Amount",
  owner: "Owner",
  taskTitle: "Task",
  type: "Type",
  priority: "Priority",
  date: "Date",
  due: "Due",
  status: "Status",
  none: "None",
  unassigned: "Unassigned",
  quietWeek: "Quiet week — no leads, activities, or deals recorded in this range.",
  byNumbers: "By the numbers",
  byNarrative: "In words",
};

function fmtCurrency(n: number | null | undefined, lang: NarrativeLang): string {
  if (n == null) return "—";
  const locale = lang === "he" ? "he-IL" : "en-US";
  return new Intl.NumberFormat(locale, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
}

function fmtDate(iso: string, lang: NarrativeLang): string {
  const date = new Date(iso);
  const locale = lang === "he" ? "he-IL" : "en-GB";
  return date.toLocaleDateString(locale, { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" });
}

function fmtShortDate(iso: string, lang: NarrativeLang): string {
  const locale = lang === "he" ? "he-IL" : "en-GB";
  return new Date(iso).toLocaleDateString(locale, { day: "numeric", month: "short" });
}

function fmtDateTime(iso: string, lang: NarrativeLang): string {
  const locale = lang === "he" ? "he-IL" : "en-GB";
  return new Date(iso).toLocaleString(locale);
}

export default function WeeklyReportPrintView({
  summary,
  narrative: initialNarrative,
  lang: initialLang,
}: {
  summary: Summary;
  narrative: WeeklyNarrative | null;
  lang: NarrativeLang;
}) {
  const [lang, setLang] = useState<NarrativeLang>(initialLang);
  const [narrative, setNarrative] = useState<WeeklyNarrative | null>(initialNarrative);
  const [regenerating, setRegenerating] = useState(false);

  const s = lang === "he" ? STRINGS_HE : STRINGS_EN;
  const dir = lang === "he" ? "rtl" : "ltr";
  const { totals, byOwner, byLeadType, bySource, topNewLeads, topWins, tasksCompletedList, tasksInProgressList } = summary.data;
  const content: NarrativeContent | null = narrative ? narrative[lang] : null;

  async function handleRegenerate() {
    setRegenerating(true);
    try {
      const res = await fetch(`/api/weekly-summaries/${summary.id}/narrative`, { method: "POST" });
      const result = await res.json();
      if (res.ok && result.narrative) {
        setNarrative(result.narrative);
      } else {
        alert(result.error ?? "Failed to regenerate");
      }
    } catch {
      alert("Network error");
    } finally {
      setRegenerating(false);
    }
  }

  function switchLang() {
    const next: NarrativeLang = lang === "he" ? "en" : "he";
    setLang(next);
    const url = new URL(window.location.href);
    url.searchParams.set("lang", next);
    window.history.replaceState({}, "", url.toString());
  }

  return (
    <>
      <style jsx global>{`
        @page {
          size: A4;
          margin: 12mm 14mm;
        }
        @media print {
          body { background: white !important; }
          .no-print { display: none !important; }
          .print-page { box-shadow: none !important; padding: 0 !important; max-width: none !important; }
          .avoid-break { page-break-inside: avoid; }
          h1, h2, h3 { page-break-after: avoid; }
        }
        body { background: #f4f5f7; }
      `}</style>

      <div
        dir={dir}
        lang={lang}
        style={{
          fontFamily:
            lang === "he"
              ? '"Heebo", "Assistant", system-ui, -apple-system, "Segoe UI", sans-serif'
              : 'system-ui, -apple-system, "Segoe UI", "Inter", sans-serif',
          color: "#0f172a",
          minHeight: "100vh",
        }}
      >
        {/* Toolbar — hidden in print */}
        <div
          className="no-print"
          style={{
            position: "sticky",
            top: 0,
            zIndex: 50,
            background: "white",
            borderBottom: "1px solid #e5e7eb",
            padding: "12px 24px",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            gap: 12,
            flexWrap: "wrap",
          }}
        >
          <Link
            href="/reports/weekly"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 6,
              fontSize: 14,
              fontWeight: 600,
              color: "#4f46e5",
              textDecoration: "none",
            }}
          >
            <ArrowLeft size={16} style={{ transform: lang === "he" ? "scaleX(-1)" : "none" }} />
            {s.back}
          </Link>

          <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
            <button
              onClick={switchLang}
              style={{
                padding: "8px 14px",
                fontSize: 13,
                fontWeight: 700,
                borderRadius: 10,
                border: "1px solid #e5e7eb",
                background: "white",
                cursor: "pointer",
              }}
            >
              {s.switchLang}
            </button>
            <button
              onClick={handleRegenerate}
              disabled={regenerating}
              style={{
                padding: "8px 14px",
                fontSize: 13,
                fontWeight: 700,
                borderRadius: 10,
                border: "1px solid #c7d2fe",
                background: "#eef2ff",
                color: "#4338ca",
                cursor: regenerating ? "default" : "pointer",
                opacity: regenerating ? 0.6 : 1,
                display: "inline-flex",
                alignItems: "center",
                gap: 6,
              }}
            >
              {regenerating ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
              {regenerating ? s.regenerating : s.regenerateAI}
            </button>
            <button
              onClick={() => window.print()}
              style={{
                padding: "8px 14px",
                fontSize: 13,
                fontWeight: 700,
                borderRadius: 10,
                border: "none",
                background: "linear-gradient(135deg,#6366f1,#8b5cf6)",
                color: "white",
                cursor: "pointer",
                display: "inline-flex",
                alignItems: "center",
                gap: 6,
                boxShadow: "0 2px 6px rgba(99,102,241,0.35)",
              }}
            >
              <Download size={14} />
              {s.download}
            </button>
          </div>
        </div>

        {/* Page */}
        <div
          className="print-page"
          style={{
            maxWidth: 880,
            margin: "0 auto",
            padding: "32px 28px 64px",
            background: "white",
            boxShadow: "0 1px 4px rgba(0,0,0,0.05)",
            marginTop: 16,
            marginBottom: 32,
            borderRadius: 16,
          }}
        >
          {/* Header banner */}
          <div
            className="avoid-break"
            style={{
              background: "linear-gradient(135deg,#4f46e5 0%,#7c3aed 50%,#9333ea 100%)",
              color: "white",
              padding: "28px 28px",
              borderRadius: 14,
              marginBottom: 28,
              boxShadow: "0 4px 14px rgba(79,70,229,0.18)",
            }}
          >
            <div style={{ fontSize: 12, fontWeight: 700, opacity: 0.85, letterSpacing: 1, textTransform: "uppercase" }}>
              {s.reportTitle}
            </div>
            <div style={{ fontSize: 28, fontWeight: 900, marginTop: 6, lineHeight: 1.15 }}>
              {fmtDate(summary.weekStart, lang)} – {fmtDate(summary.weekEnd, lang)}
            </div>
            {content?.headline && (
              <div style={{ fontSize: 15, marginTop: 14, opacity: 0.95, fontWeight: 500, lineHeight: 1.5 }}>
                {content.headline}
              </div>
            )}
            <div style={{ fontSize: 11, marginTop: 14, opacity: 0.75 }}>
              {s.generatedAt}: {fmtDateTime(summary.generatedAt, lang)}
            </div>
          </div>

          {/* KPI grid */}
          <Section title={s.keyNumbers} accent>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(4, 1fr)",
                gap: 12,
              }}
            >
              <Kpi label={s.newLeads} value={totals.newLeads} color="#4f46e5" lang={lang} />
              <Kpi label={s.activities} value={totals.activities} color="#0891b2" lang={lang} />
              <Kpi label={s.dealsWon} value={totals.wonDeals} hint={fmtCurrency(totals.wonAmount, lang)} color="#15803d" lang={lang} />
              <Kpi label={s.dealsLost} value={totals.lostDeals} color="#b91c1c" lang={lang} />
              <Kpi label={s.calls} value={totals.callsCount} color="#6366f1" lang={lang} />
              <Kpi label={s.meetings} value={totals.meetingsCount} color="#7c3aed" lang={lang} />
              <Kpi label={s.emails} value={totals.emailsCount} color="#0e7490" lang={lang} />
              <Kpi label={s.messages} value={totals.messagesCount} color="#a16207" lang={lang} />
              <Kpi label={s.stageChanges} value={totals.stageChanges} color="#4338ca" lang={lang} />
              <Kpi label={s.tasksCreated} value={totals.tasksCreated} color="#0891b2" lang={lang} />
              <Kpi label={s.tasksCompleted} value={totals.tasksCompleted} color="#15803d" lang={lang} />
              <Kpi label={s.notes} value={totals.notesCount} color="#525252" lang={lang} />
            </div>
          </Section>

          {/* AI narrative */}
          {content ? (
            <>
              <Section title={s.executiveSummary} accent>
                <p style={paragraphStyle}>{content.executiveSummary}</p>
              </Section>

              <Section title={s.leadAcquisition}>
                <p style={paragraphStyle}>{content.leadAcquisition}</p>
              </Section>

              <Section title={s.pipelineProgress}>
                <p style={paragraphStyle}>{content.pipelineProgress}</p>
              </Section>

              <Section title={s.tasksWork}>
                <p style={paragraphStyle}>{content.tasksWork}</p>
              </Section>

              {content.highlights.length > 0 && (
                <Section title={s.highlights} variant="success">
                  <BulletList items={content.highlights} color="#15803d" />
                </Section>
              )}

              {content.concerns.length > 0 && (
                <Section title={s.concerns} variant="warning">
                  <BulletList items={content.concerns} color="#b45309" />
                </Section>
              )}

              {content.recommendations.length > 0 && (
                <Section title={s.recommendations} variant="info">
                  <BulletList items={content.recommendations} color="#4338ca" />
                </Section>
              )}

              <p style={{ fontSize: 10, color: "#94a3b8", marginTop: 18, fontStyle: "italic", textAlign: "center" }}>
                {s.aiGeneratedNote}
              </p>
            </>
          ) : (
            <div
              className="no-print avoid-break"
              style={{
                background: "#f1f5f9",
                border: "1px dashed #cbd5e1",
                color: "#475569",
                padding: 18,
                borderRadius: 10,
                fontSize: 14,
                marginBottom: 22,
                textAlign: "center",
              }}
            >
              <Sparkles size={20} style={{ color: "#6366f1", marginBottom: 6 }} />
              <div>{s.aiUnavailable}</div>
            </div>
          )}

          {/* By agent */}
          {byOwner.length > 0 && (
            <Section title={s.byAgent}>
              <Table
                headers={[s.agentName, s.newLeadsCol, s.activitiesCol, s.wonDealsCol, s.wonAmountCol]}
                rows={byOwner.slice(0, 12).map((o) => [
                  o.ownerName,
                  String(o.newLeads),
                  String(o.activities),
                  String(o.wonDeals),
                  fmtCurrency(o.wonAmount, lang),
                ])}
                dir={dir}
              />
            </Section>
          )}

          {/* By lead type + source side-by-side */}
          {(byLeadType.length > 0 || bySource.length > 0) && (
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 22 }} className="avoid-break">
              {byLeadType.length > 0 && (
                <MiniListCard
                  title={s.byLeadType}
                  rows={byLeadType.map((t) => ({ label: t.typeName, value: t.newLeads }))}
                  dir={dir}
                />
              )}
              {bySource.length > 0 && (
                <MiniListCard
                  title={s.bySource}
                  rows={bySource.slice(0, 10).map((b) => ({ label: b.source, value: b.count }))}
                  dir={dir}
                />
              )}
            </div>
          )}

          {/* Top new leads */}
          {topNewLeads.length > 0 && (
            <Section title={s.topNewLeads}>
              <Table
                headers={[s.leadName, s.company, s.amount, s.owner]}
                rows={topNewLeads.map((l) => [
                  l.displayName,
                  l.companyName ?? "—",
                  fmtCurrency(l.potentialAmount, lang),
                  l.ownerName ?? s.unassigned,
                ])}
                dir={dir}
              />
            </Section>
          )}

          {/* Top wins */}
          {topWins.length > 0 && (
            <Section title={s.topWins} variant="success">
              <Table
                headers={[s.leadName, s.company, s.amount, s.owner]}
                rows={topWins.map((l) => [
                  l.displayName,
                  l.companyName ?? "—",
                  fmtCurrency(l.closedAmount, lang),
                  l.ownerName ?? s.unassigned,
                ])}
                dir={dir}
              />
            </Section>
          )}

          {/* Tasks completed */}
          {tasksCompletedList && tasksCompletedList.length > 0 && (
            <Section title={s.tasksCompletedList} variant="success">
              <Table
                headers={[s.taskTitle, s.date, s.leadName, s.owner, s.priority]}
                rows={tasksCompletedList.slice(0, 30).map((t) => [
                  t.title,
                  fmtShortDate(t.completedAt, lang),
                  t.leadName ?? "—",
                  t.assigneeName ?? "—",
                  t.priority,
                ])}
                dir={dir}
              />
            </Section>
          )}

          {/* Tasks in progress */}
          {tasksInProgressList && tasksInProgressList.length > 0 && (
            <Section title={s.tasksInProgressList} variant="warning">
              <Table
                headers={[s.taskTitle, s.due, s.leadName, s.owner, s.priority]}
                rows={tasksInProgressList.slice(0, 30).map((t) => [
                  t.title,
                  t.dueAt ? fmtShortDate(t.dueAt, lang) : "—",
                  t.leadName ?? "—",
                  t.assigneeName ?? "—",
                  t.priority,
                ])}
                dir={dir}
              />
            </Section>
          )}
        </div>
      </div>
    </>
  );
}

/* ============================ helpers ============================ */

const paragraphStyle: React.CSSProperties = {
  fontSize: 14.5,
  lineHeight: 1.7,
  color: "#334155",
  margin: 0,
};

function Section({
  title,
  children,
  variant,
  accent,
}: {
  title: string;
  children: React.ReactNode;
  variant?: "success" | "warning" | "info";
  accent?: boolean;
}) {
  const variantBg: Record<string, string> = {
    success: "#f0fdf4",
    warning: "#fffbeb",
    info: "#eef2ff",
  };
  const variantBorder: Record<string, string> = {
    success: "#bbf7d0",
    warning: "#fde68a",
    info: "#c7d2fe",
  };
  const variantTitleColor: Record<string, string> = {
    success: "#15803d",
    warning: "#b45309",
    info: "#4338ca",
  };

  return (
    <div
      className="avoid-break"
      style={{
        marginBottom: 22,
        background: variant ? variantBg[variant] : "white",
        border: variant ? `1px solid ${variantBorder[variant]}` : "1px solid #e5e7eb",
        borderRadius: 12,
        padding: "16px 18px",
      }}
    >
      <h3
        style={{
          fontSize: 13,
          fontWeight: 900,
          textTransform: "uppercase",
          letterSpacing: 1.2,
          color: variant ? variantTitleColor[variant] : accent ? "#4338ca" : "#475569",
          margin: "0 0 12px 0",
        }}
      >
        {title}
      </h3>
      {children}
    </div>
  );
}

function Kpi({
  label,
  value,
  hint,
  color,
  lang,
}: {
  label: string;
  value: string | number;
  hint?: string;
  color: string;
  lang: NarrativeLang;
}) {
  const display = typeof value === "number" ? value.toLocaleString(lang === "he" ? "he-IL" : "en-US") : value;
  return (
    <div
      style={{
        background: "white",
        border: "1px solid #e5e7eb",
        borderInlineStart: `3px solid ${color}`,
        borderRadius: 10,
        padding: "10px 12px",
        minHeight: 60,
      }}
    >
      <div style={{ fontSize: 10, fontWeight: 700, color: "#94a3b8", textTransform: "uppercase", letterSpacing: 0.8 }}>
        {label}
      </div>
      <div style={{ fontSize: 22, fontWeight: 900, color: "#0f172a", lineHeight: 1.1, marginTop: 4 }}>{display}</div>
      {hint && <div style={{ fontSize: 11, color: "#64748b", marginTop: 2 }}>{hint}</div>}
    </div>
  );
}

function BulletList({ items, color }: { items: string[]; color: string }) {
  return (
    <ul style={{ margin: 0, paddingInlineStart: 18, fontSize: 14, lineHeight: 1.7, color: "#334155" }}>
      {items.map((it, i) => (
        <li key={i} style={{ marginBottom: 4 }}>
          <span style={{ color, fontWeight: 700 }}>•</span> {it}
        </li>
      ))}
    </ul>
  );
}

function Table({
  headers,
  rows,
  dir,
}: {
  headers: string[];
  rows: string[][];
  dir: "ltr" | "rtl";
}) {
  return (
    <div style={{ overflow: "hidden", borderRadius: 8, border: "1px solid #e5e7eb" }}>
      <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12.5, direction: dir }}>
        <thead style={{ background: "#f8fafc" }}>
          <tr>
            {headers.map((h, i) => (
              <th
                key={i}
                style={{
                  textAlign: dir === "rtl" ? "right" : "left",
                  padding: "8px 10px",
                  fontWeight: 800,
                  color: "#475569",
                  fontSize: 11,
                  textTransform: "uppercase",
                  letterSpacing: 0.6,
                  borderBottom: "1px solid #e5e7eb",
                }}
              >
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, ri) => (
            <tr key={ri} style={{ borderBottom: ri === rows.length - 1 ? "none" : "1px solid #f1f5f9" }}>
              {row.map((cell, ci) => (
                <td
                  key={ci}
                  style={{
                    padding: "8px 10px",
                    color: ci === 0 ? "#0f172a" : "#475569",
                    fontWeight: ci === 0 ? 600 : 500,
                    textAlign: dir === "rtl" ? "right" : "left",
                  }}
                >
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function MiniListCard({
  title,
  rows,
  dir,
}: {
  title: string;
  rows: Array<{ label: string; value: number }>;
  dir: "ltr" | "rtl";
}) {
  return (
    <div
      style={{
        background: "white",
        border: "1px solid #e5e7eb",
        borderRadius: 12,
        padding: "14px 16px",
      }}
    >
      <h3 style={{ fontSize: 12, fontWeight: 900, textTransform: "uppercase", letterSpacing: 1.1, color: "#475569", margin: "0 0 10px 0" }}>
        {title}
      </h3>
      <div style={{ direction: dir }}>
        {rows.map((r, i) => (
          <div
            key={i}
            style={{
              display: "flex",
              justifyContent: "space-between",
              padding: "5px 0",
              borderBottom: i === rows.length - 1 ? "none" : "1px solid #f1f5f9",
              fontSize: 13,
            }}
          >
            <span style={{ fontWeight: 600, color: "#0f172a" }}>{r.label}</span>
            <span
              style={{
                fontWeight: 800,
                color: "#4338ca",
                background: "#eef2ff",
                padding: "1px 10px",
                borderRadius: 999,
                fontSize: 11,
              }}
            >
              {r.value}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}
